sampling:
  ratio: "15"
  
server:
  port: "8401"
  
spring:
  kafka:
    consumer-topic: "SOIL_DATA"
    producer-topic: "IRRIGATION_ALERT"
    consumer:
      bootstrap-servers: "pkc-75m1o.europe-west3.gcp.confluent.cloud:9092"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      spring.kafka.consumer.properties.spring.json.trusted.packages: "*"
      group-id: kpi-measures-listiner-group
