sampling:
  ratio: "15"

server:
  port: "8401"

mongo:
    user: "kpi-measures-user"
    password: "Ny3a8u541M796Imf"
    host: "mongodb+srv://${mongo.user}:${mongo.password}@db-mongodb-nyc1-71962-6157d0c7.mongo.ondigitalocean.com/kpi-measures-db?tls=true&authSource=admin&replicaSet=db-mongodb-nyc1-71962"
    port: "27017"
    
spring:
  data:
    mongodb:
      port: ${mongo.port}
      uri: ${mongo.host}
  kafka:
    consumer-topic: "SOIL_DATA"
    producer-topic: "IRRIGATION_ALERT"
    jaas:
      enabled: "true"
    properties:
      auto-offset-reset: "latest"
      json:
        use:
          type:
            headers: "false"
            key: "false"
      security:
        protocol: "SASL_SSL"
      sasl:
        mechanism: "PLAIN"
        jaas:
          config: "org.apache.kafka.common.security.plain.PlainLoginModule required username = '3ON4VM2WFBCNBPK6' password = 'ZNqvcPq6oy6mf8tOjHziXHx0kgfhDt3+30LX02KO3bm7tTxnUf0M2P2rEl6QUSj2';"
    consumer:
      bootstrap-servers: "pkc-75m1o.europe-west3.gcp.confluent.cloud:9092"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      group-id: "ci-cm-kpi-measures-consumer-group"
