sampling:
  ratio: "15"

server:
  port: "8401"

spring:
  kafka:
    consumer-topic: "SOIL_DATA"
    producer-topic: "IRRIGATION_ALERT"
    jaas:
      enabled: "true"
    properties:
      security:
        protocol: "SASL_SSL"
      sasl:
        mechanism: "PLAIN"
        jaas:
          config: "org.apache.kafka.common.security.plain.PlainLoginModule required username = '3ON4VM2WFBCNBPK6' password = 'ZNqvcPq6oy6mf8tOjHziXHx0kgfhDt3+30LX02KO3bm7tTxnUf0M2P2rEl6QUSj2'"
    consumer:
      bootstrap-servers: "pkc-75m1o.europe-west3.gcp.confluent.cloud:9092"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      spring.kafka.consumer.properties.spring.json.trusted.packages: "*"
      group-id: "kpi-measures-listiner-group"
